processes:
  - name: "example-service"
    command: "/bin/sh"
    args: ["-c", "echo 'running'; sleep 3; exit 0"]
    start_timeout: "1s"
    restart_delay: "5s"
    max_restarts: 5
    working_dir: "/Users/sorin.panduru/work/go/goardian"
    environment:
      - "ENV=production"
      - "DEBUG=false"
    backoff_enabled: true
    backoff_factor: 2.0
    backoff_max_delay: "1m" 