# Global configuration
log_format: "console"  # or "json"
metrics_addr: ":9090"
shutdown_delay: "30s"  # How long to wait for all processes to shutdown

# Process configurations
processes:
  - name: "randomsleeper 1"
    command: "/usr/local/bin/randomsleeper"
    args: ["-processid", "1"]
    working_dir: "."
    environment:
      - "APP_ENV=prod"
      - "APP_DEBUG=0"
    numprocs: 1
    start_timeout: "1s"
    stop_timeout: "3s"
    restart_delay: "3s"
    max_restarts: 10
    backoff_enabled: true
    backoff_factor: 1.5
    backoff_max_delay: "1m"
    exit_codes: [0] 
  - name: "randomsleeper 6"
    command: "/usr/local/bin/randomsleeper"
    args: ["-processid", "6"]
    working_dir: "."
    environment:
      - "APP_ENV=prod"
      - "APP_DEBUG=0"
    numprocs: 4
    start_timeout: "1s"
    stop_timeout: "3s"
    restart_delay: "3s"
    max_restarts: 10
    backoff_enabled: true
    backoff_factor: 1.5
    backoff_max_delay: "1m"
    exit_codes: [0] 
  - name: "randomsleeper 0"
    command: "/usr/local/bin/randomsleeper"
    args: ["-processid", "0"]
    working_dir: "."
    environment:
      - "APP_ENV=prod"
      - "APP_DEBUG=0"
    numprocs: 4
    start_timeout: "1s"
    stop_timeout: "3s"
    restart_delay: "3s"
    max_restarts: 10
    backoff_enabled: true
    backoff_factor: 1.5
    backoff_max_delay: "1m"
    exit_codes: [0] 
  - name: "randomsleeper 2"
    command: "/usr/local/bin/randomsleeper"
    args: ["-processid", "2"]
    working_dir: "."
    environment:
      - "APP_ENV=prod"
      - "APP_DEBUG=0"
    numprocs: 4
    start_timeout: "1s"
    stop_timeout: "3s"
    restart_delay: "3s"
    max_restarts: 10
    backoff_enabled: true
    backoff_factor: 1.5
    backoff_max_delay: "1m"
    exit_codes: [0] 
  - name: "randomsleeper 3"
    command: "/usr/local/bin/randomsleeper"
    args: ["-processid", "3"]
    working_dir: "."
    environment:
      - "APP_ENV=prod"
      - "APP_DEBUG=0"
    numprocs: 4
    start_timeout: "1s"
    stop_timeout: "3s"
    restart_delay: "3s"
    max_restarts: 10
    backoff_enabled: true
    backoff_factor: 1.5
    backoff_max_delay: "1m"
    exit_codes: [0] 
  - name: "randomsleeper 4"
    command: "/usr/local/bin/randomsleeper"
    args: ["-processid", "4"]
    working_dir: "."
    environment:
      - "APP_ENV=prod"
      - "APP_DEBUG=0"
    numprocs: 4
    start_timeout: "1s"
    stop_timeout: "3s"
    restart_delay: "3s"
    max_restarts: 10
    backoff_enabled: true 
    backoff_factor: 1.5
    backoff_max_delay: "1m"
    exit_codes: [0] 
  - name: "randomsleeper 5"
    command: "/usr/local/bin/randomsleeper"
    args: ["-processid", "5"]
    working_dir: "."
    environment:
      - "APP_ENV=prod"
      - "APP_DEBUG=0"
    numprocs: 4
    start_timeout: "1s"
    stop_timeout: "3s"
    restart_delay: "3s"
    max_restarts: 10
    backoff_enabled: true
    backoff_factor: 1.5
    backoff_max_delay: "1m"
    exit_codes: [0] 